"""Gemeinsame Marken-Bausteine (Logo, Favicon) fuer dashboard.html (render.py)
und die /settings-Seite (server.py) -- eine Quelle, damit beide nicht
auseinanderlaufen.

Favicon ist identisch zum Nachbarprojekt parqet-dashboard uebernommen
(Konsistenz ueber beide Pixxelpassion-Tools hinweg).
"""

from __future__ import annotations

import base64
from pathlib import Path

_LOGO_PATH = Path(__file__).resolve().parent / "assets" / "logo_pixxelpassion.webp"

FAVICON_LINK = (
    '<link rel="icon" href="data:image/x-icon;base64,'
    "AAABAAEAEBAAAAEACABoBQAAFgAAACgAAAAQAAAAIAAAAAEACAAAAAAAAAEAABILAAASCwAAAAEAAAABAADy9vUAJSw4ACs5SgBNwLMAXmRsAFPVyACGqaMAR66kAEmBewBLxrsAH3FkAD2vpAAgMUYATLuxAOvr7QA1n5QARb2yADpBTAAjM0kALUdkACY5UwBEu68AMj1LAHyjnQA/npMAIS9DACk/WgAyTm0AHSc2ABonOQBQz8IAUc7CACWBdQCas7EA3+roADBKZQAYJTUA9vf4AOby8QBJsqcAqL26AB4vQwDz8/QA+fv6ACF5bABAoZYAkZSbAMjU0gAtPFIAUM/DAB8sPQBKxLgAJDZPAK+2vwDr8O8AnrayAF+LhQBLtq0AzM/TAElbcABWh34AUtPGABskMwD29vcAV2yCAExRWwC5zssAzdvZAMrT0QCvvMAANlVzADNQbgBvd38ATMe7AE/MvwBSpZoAnba7ACp9cgBQsaYAR4uDAPL5+ADb5ugAk7GsAG9+jwB5h4sAapKOAIWPmwAzjIIAiZKcACyQhQDP0NIAbnyQAB0oNgCjpqoAgMnAADaDegDi5OUATXJtADSQhQA6mI0AQameADpGVAAwQFgAQZ6VAKqyugBveYQA5fDvAMTh3gCZtbAALHJoAFWIgwDe7uwASbGoAFGBeQDHzdIAisnCAC2EeQBOX3oA4unoAOXr6gBQzsIApLm2AEJ7cgA2SF4AUNDDAB8rPQD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfn5+fn5+JV0EEQEBAQEEf35+fn5+DkE+HBwcXBwcEX9+fn42bFQ+fTJ9fX19fRZ/fn53ejhIHRkZGRkZGRkCf34rPAooLiQZEhISEhISAn9+KAosQ2ABHSkMDBI0FDB/AHEgdCJ+WgQWAmUCFBp7fy9tWWJqfn5+Kg4/aRoTO383TQ8PayZvAH5+flgTG1N/BlcLCycHZE5zUH5WR0c1fxdjFRAQEBAQFV5+W0ZAJX8XGDNJCQkJCUkDUXUjcn5/Bi1KfB4eHjF4A0xmaH5+f1IYHwUFBT0fA0tFOn5+fn95X3ANDTkHZ09Cfn5+fn5/RGEICAhuVSF2fn5+fn5+fwABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAA="
    '">'
)


def logo_data_uri() -> str:
    """Base64-Data-URI des Pixxelpassion-Logos (WebP), leer bei Fehler."""
    try:
        data = _LOGO_PATH.read_bytes()
        b64 = base64.b64encode(data).decode("ascii")
        return f"data:image/webp;base64,{b64}"
    except Exception:
        return ""
